"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { useMemo, useState, useTransition } from "react";
import { X } from "lucide-react";
import { useRouter } from "next/navigation";
import { updateAssetGroupValueTransactions } from "@/app/actions/assets";
import { DatePicker } from "@/components/ui/date-picker";
import { formatCurrency } from "@/lib/utils";
import { Tabs, TabsList, TabsTrigger } from "@/components/motion/tabs";

type Transaction = { id: number; groupId: number; totalValue: number; totalCost: number | null; recordedAt: string };
type Group = { id: number; name: string; color: string };
const dateFormatter = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" });
const monthFormatter = new Intl.DateTimeFormat("en-US", { month: "short" });

export function TotalValueTransactions({ transactions, groups }: { transactions: Transaction[]; groups: Group[] }) {
  const [year, setYear] = useState<number | "all">("all");
  const [month, setMonth] = useState<number | "all">("all");
  const years = useMemo(() => [...new Set(transactions.map((transaction) => new Date(transaction.recordedAt).getUTCFullYear()))].sort((a, b) => b - a), [transactions]);
  const months = useMemo(() => year === "all" ? [] : [...new Set(transactions.filter((transaction) => new Date(transaction.recordedAt).getUTCFullYear() === year).map((transaction) => new Date(transaction.recordedAt).getUTCMonth()))].sort((a, b) => a - b), [transactions, year]);
  const filtered = transactions.filter((transaction) => (year === "all" || new Date(transaction.recordedAt).getUTCFullYear() === year) && (month === "all" || new Date(transaction.recordedAt).getUTCMonth() === month));
  const buttonClass = (active: boolean) => active ? "h-8 whitespace-nowrap rounded-lg px-2.5 text-xs font-extrabold text-[#10140a] hover:text-[#10140a]" : "h-8 whitespace-nowrap rounded-lg bg-soft px-2.5 text-xs font-bold text-muted hover:text-ink";

  return <div className="mt-5 border-t border-line pt-4"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-bold text-muted">Total value transactions</p><p className="text-[11px] text-muted">{filtered.length} shown</p></div><div className="space-y-2"><Tabs value={String(year)} onValueChange={(value) => { setYear(value === "all" ? "all" : Number(value)); setMonth("all"); }} variant="segment"><TabsList className="flex w-full gap-1.5 overflow-x-auto rounded-none border-0 bg-transparent p-0 [&>div]:shrink-0"><TabsTrigger value="all" className={buttonClass(year === "all")} indicatorClassName="bg-accent">All years</TabsTrigger>{years.map((item) => <TabsTrigger key={item} value={String(item)} className={buttonClass(year === item)} indicatorClassName="bg-accent">{item}</TabsTrigger>)}</TabsList></Tabs>{year !== "all" && <Tabs value={String(month)} onValueChange={(value) => setMonth(value === "all" ? "all" : Number(value))} variant="segment"><TabsList className="flex w-full gap-1.5 overflow-x-auto rounded-none border-0 bg-transparent p-0 [&>div]:shrink-0"><TabsTrigger value="all" className={buttonClass(month === "all")} indicatorClassName="bg-accent">All months</TabsTrigger>{months.map((item) => <TabsTrigger key={item} value={String(item)} className={buttonClass(month === item)} indicatorClassName="bg-accent">{monthFormatter.format(new Date(Date.UTC(2026, item, 1)))}</TabsTrigger>)}</TabsList></Tabs>}</div>{filtered.length === 0 ? <p className="py-4 text-center text-xs text-muted">No total value transactions for this period.</p> : <div className="mt-3 max-h-96 space-y-2 overflow-y-auto pr-1">{filtered.map((transaction) => { const group = groups.find((item) => item.id === transaction.groupId); return <EditTransaction key={transaction.id} transaction={transaction} trigger={<button type="button" className="flex w-full items-center justify-between gap-3 rounded-xl border border-line bg-canvas px-3 py-2.5 text-left hover:border-[#4b5547]"><div className="min-w-0"><p className="flex items-center gap-2 truncate text-sm font-bold"><span className="size-2 shrink-0 rounded-full" style={{ backgroundColor: group?.color ?? "#c8ff52" }}/>{group?.name ?? "Deleted group"}</p><p className="mt-0.5 text-[11px] text-muted">{dateFormatter.format(new Date(transaction.recordedAt))}</p></div><span className="text-sm font-extrabold">{formatCurrency(transaction.totalValue, "THB")}</span></button>}/>; })}</div>}</div>;
}

function EditTransaction({ transaction, trigger }: { transaction: Transaction; trigger: React.ReactNode }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [amount, setAmount] = useState(String(transaction.totalValue)); const [cost, setCost] = useState(transaction.totalCost?.toString() ?? ""); const [date, setDate] = useState(transaction.recordedAt.slice(0, 10)); const [pending, startTransition] = useTransition();
  function save() { const formData = new FormData(); formData.set("recordedAt", date); formData.set("updates", JSON.stringify([{ id: transaction.id, totalValue: Number(amount), totalCost: cost === "" ? null : Number(cost) }])); startTransition(async () => { const result = await updateAssetGroupValueTransactions(formData); if (result.success) { setOpen(false); router.refresh(); } }); }
  return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild>{trigger}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay dialog-overlay-motion"/><Dialog.Content className="asset-dialog dialog-sheet-motion"><div className="flex items-start justify-between gap-4"><div><Dialog.Title className="text-xl font-extrabold">Edit total value</Dialog.Title></div><Dialog.Close className="icon-button"><X size={17}/></Dialog.Close></div><div className="mt-6 space-y-4"><label className="auth-field"><span>Total value (THB)</span><div><input type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)}/></div></label><label className="auth-field"><span>Total cost (THB, optional)</span><div><input type="number" min="0" step="0.01" placeholder="0.00" value={cost} onChange={(event) => setCost(event.target.value)}/></div></label><div className="auth-field"><span>Recorded date</span><div className="!block !h-auto !border-0 !bg-transparent !p-0"><DatePicker name="date" value={date} onChange={setDate} required label="Select date"/></div></div><button type="button" disabled={pending || !amount || !date} onClick={save} className="auth-submit">Save changes</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
